FROM golang:1.14-alpine

RUN apk update && \
    apk add git curl build-base make openssh-client

WORKDIR /app 

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

ENV GOCACHE=/tmp/build

CMD air -c .air.api.toml
