version: '3.8'

services:

  user:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: user
    ports:
      - 8081:8080
    depends_on:
      - mysql_user_read
      - mysql_user_write
    volumes:
      - ./:/app
    environment:
      USER_HOST: 0.0.0.0
      AUTH_DBHOSTREADER: mysql_user_read
      AUTH_DBPORTREADER: 3306
      AUTH_DBHOSTWRITER: mysql_user_write
      AUTH_DBPORTWRITER: 3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/health"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  mysql_user:
  user-build:
